/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// would hide this normally but for the sake of the demo i've made it public
const awsmobile = {
	aws_project_region: "eu-west-1",
	aws_cognito_identity_pool_id:
		"eu-west-1:2d3986ac-8f82-40e0-b540-9e36f009f775",
	aws_cognito_region: "eu-west-1",
	aws_user_pools_id: "eu-west-1_SZ03e4m1J",
	aws_user_pools_web_client_id: "5h3nqm3i2tbs4271j8cl91vm89",
	oauth: {},
};

export default awsmobile;
